import fs from "fs";
import path from "path";

const fotosDir = path.join(process.cwd(), "public", "fotos");
const outputFile = path.join(process.cwd(), "lib", "catalog.generated.ts");
const fileRegex = /^([A-Za-z0-9]+)(?:-(\d+))?\.([a-zA-Z0-9]+)$/;

const rawFiles = fs.readdirSync(fotosDir);
const codeInfo = new Map<string, { mainExt?: string; variantCount: number; extensions: Set<string> }>();
for (const file of rawFiles) {
  const match = file.match(fileRegex);
  if (!match) continue;

  const [, code, idxStr, ext] = match;
  const existing = codeInfo.get(code) ?? { variantCount: 0, extensions: new Set<string>() };
  existing.extensions.add(ext);
  if (idxStr === undefined) {
    existing.mainExt = ext;
  } else {
    const idx = Number(idxStr);
    if (!Number.isNaN(idx) && idx > existing.variantCount) {
      existing.variantCount = idx;
    }
  }
  codeInfo.set(code, existing);
}

const rawCodes = Array.from(codeInfo.entries())
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([code, info]) => ({
    code,
    mainExt: info.mainExt ?? Array.from(info.extensions)[0] ?? "png",
    variantCount: info.variantCount,
  }));

const contents = `// This file is generated by scripts/generate-catalog.ts
// Do not edit directly.

export const rawCodes = ${JSON.stringify(rawCodes, null, 2)} as const;
`;

fs.writeFileSync(outputFile, contents, "utf8");
console.log(`Generated ${outputFile} with ${rawCodes.length} catalog entries.`);
