const fs = require("fs");
const path = require("path");

const fotosDir = path.join(process.cwd(), "public", "fotos");
const outputFile = path.join(process.cwd(), "lib", "catalog.generated.ts");
const fileRegex = /^([A-Za-z0-9]+)(?:-(\d+))?\.([a-zA-Z0-9]+)$/;

const rawFiles = fs.readdirSync(fotosDir);
const codeInfo = new Map();
for (const file of rawFiles) {
  const match = file.match(fileRegex);
  if (!match) continue;
  const code = match[1];
  const idxStr = match[2];
  const ext = match[3];
  const info = codeInfo.get(code) || { mainExt: undefined, variantCount: 0, extensions: new Set() };
  info.extensions.add(ext);
  if (idxStr === undefined) {
    info.mainExt = ext;
  } else {
    const idx = Number(idxStr);
    if (!Number.isNaN(idx) && idx > info.variantCount) {
      info.variantCount = idx;
    }
  }
  codeInfo.set(code, info);
}

const rawCodes = Array.from(codeInfo.entries())
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([code, info]) => ({
    code,
    mainExt: info.mainExt || Array.from(info.extensions)[0] || "png",
    variantCount: info.variantCount,
  }));

const contents = `// This file is generated by scripts/generate-catalog.js\n// Do not edit directly.\n\nexport const rawCodes = ${JSON.stringify(rawCodes, null, 2)} as const;\n`;
fs.writeFileSync(outputFile, contents, "utf8");
console.log(`Generated ${outputFile} with ${rawCodes.length} catalog entries.`);
